@startuml
title Produktionsablauf EVO2 Lightweight

actor Kunde
participant "Odoo MRP" as Odoo
participant "Shopfloor-Steuerung" as SFS

Kunde -> Odoo : Kundenauftrag anlegen
Odoo -> Odoo : Fertigungsauftrag erzeugen
Odoo -> SFS : Produktionsauftrag freigeben

SFS -> SFS : 10 - 3D-Druck Füße (WC-3D)
activate SFS
SFS -> Odoo : Buchung / Fortschritt melden
deactivate SFS

SFS -> SFS : 20 - 3D-Druck Haube (WC-3D)
activate SFS
SFS -> Odoo : Buchung / Fortschritt melden
deactivate SFS

SFS -> SFS : 30 - Laserschneiden Grundplatte (WC-LC)
activate SFS
SFS -> Odoo : Buchung / Fortschritt melden
deactivate SFS

SFS -> SFS : 40 - Nacharbeit Grundplatte (WC-NACH)
activate SFS
SFS -> Odoo : Buchung / Fortschritt melden
deactivate SFS

SFS -> SFS : 50 - Nacharbeit Füße (WC-NACH)
activate SFS
SFS -> Odoo : Buchung / Fortschritt melden
deactivate SFS

SFS -> SFS : 60 - Nacharbeit Haube (WC-NACH)
activate SFS
SFS -> Odoo : Buchung / Fortschritt melden
deactivate SFS

SFS -> SFS : 70 - WT bestücken (WC-WTB)
activate SFS
SFS -> Odoo : Buchung / Fortschritt melden
deactivate SFS

SFS -> SFS : 80 - Löten Elektronik (WC-LOET)
activate SFS
SFS -> Odoo : Buchung / Fortschritt melden
deactivate SFS

SFS -> SFS : 90 - Montage Elektronik (WC-MONT1)
activate SFS
SFS -> Odoo : Buchung / Fortschritt melden
deactivate SFS

SFS -> SFS : 100 - Flashen Flugcontroller (WC-FLASH)
activate SFS
SFS -> Odoo : Buchung / Fortschritt melden
deactivate SFS

SFS -> SFS : 110 - Montage Gehäuse & Rotoren (WC-MONT2)
activate SFS
SFS -> Odoo : Buchung / Fortschritt melden
deactivate SFS

SFS -> SFS : 120 - End-Qualitätskontrolle (WC-QM-END)
activate SFS
SFS -> Odoo : Buchung / Fortschritt melden
deactivate SFS

SFS -> Odoo : Fertigmeldung Drohne
Odoo -> Kunde : Lieferung / Abschluss

@enduml